# Play2048
#     game_board
#     new_random_tiles
#     score
#     high_score
#     game_score
#     highest_score
#   __init__
#     button_frame
#   canvas
#   new_tiles
#   full
#   show_board
#     square
#   show_number()
#   show_number
#   moves
#   new_game
#   game_over
#   game_won
#     app